version: "2.3"

services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: node.dockerfile
    volumes:
      - ./front:/front
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: sh -c "npm run serve"